/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScaleCard {
        /**
          * (optional) Label of the card
         */
        "label"?: string;
        /**
          * (optional) Link card rel
         */
        "rel"?: string;
        /**
          * (optional) Injected CSS styles
         */
        "styles"?: string;
        /**
          * (optional) Link card target
         */
        "target"?: string;
        /**
          * (optional) Link card
         */
        "to"?: string;
    }
}
declare global {
    interface HTMLScaleCardElement extends Components.ScaleCard, HTMLStencilElement {
    }
    var HTMLScaleCardElement: {
        prototype: HTMLScaleCardElement;
        new (): HTMLScaleCardElement;
    };
    interface HTMLElementTagNameMap {
        "scale-card": HTMLScaleCardElement;
    }
}
declare namespace LocalJSX {
    interface ScaleCard {
        /**
          * (optional) Label of the card
         */
        "label"?: string;
        /**
          * (optional) Link card rel
         */
        "rel"?: string;
        /**
          * (optional) Injected CSS styles
         */
        "styles"?: string;
        /**
          * (optional) Link card target
         */
        "target"?: string;
        /**
          * (optional) Link card
         */
        "to"?: string;
    }
    interface IntrinsicElements {
        "scale-card": ScaleCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scale-card": LocalJSX.ScaleCard & JSXBase.HTMLAttributes<HTMLScaleCardElement>;
        }
    }
}
